name: cmds
description: Acompanhamento de dados

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  cloud_firestore: ^0.13.0+1
  firebase_storage: ^3.1.1
  http: ^0.12.0+4
  charts_flutter: ^0.9.0
  font_awesome_flutter: ^8.2.0
  flutter_staggered_grid_view: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/
